module.exports.specialties = [
"Psychiatrist",
"Psychologist",
"Clinical Psychologist",
"Counselling Psychologist",
"Psychotherapist",
]

const tierTwo = [
    "Agra",
    "Ajmer",
    "Aligarh",
    "Amravati",
    "Amritsar",
    "Asansol",
    "Aurangabad",
    "Bareilly",
    "Belgaum",
    "Bhavnagar",
    "Bhiwandi",
    "Bhopal",
    "Bhubaneswar",
    "Bikaner",
    "Bilaspur",
    "Bokaro Steel City",
    "Chandigarh",
    "Coimbatore",
    "Cuttack",
    "Dehradun",
    "Dhanbad",
    "Bhilai",
    "Durgapur",
    "Dindigul",
    "Erode",
    "Faridabad",
    "Firozabad",
    "Ghaziabad",
    "Gorakhpur",
    "Gulbarga",
    "Guntur",
    "Gwalior",
    "Gurgaon",
    "Guwahati",
    "Hamirpur",
    "Hubli–Dharwad",
    "Indore",
    "Jabalpur",
    "Jaipur",
    "Jalandhar",
    "Jammu",
    "Jamnagar",
    "Jamshedpur",
    "Jhansi",
    "Jodhpur",
    "Kakinada",
    "Kannur",
    "Kanpur",
    "Karnal",
    "Kochi",
    "Kolhapur",
    "Kollam",
    "Kozhikode",
    "Kurnool",
    "Ludhiana",
    "Lucknow",
    "Madurai",
    "Malappuram",
    "Mathura",
    "Mangalore",
    "Meerut",
    "Moradabad",
    "Mysore",
    "Nagpur",
    "Nanded",
    "Nashik",
    "Nellore",
    "Noida",
    "Patna",
    "Pondicherry",
    "Purulia",
    "Prayagraj",
    "Raipur",
    "Rajkot",
    "Rajahmundry",
    "Ranchi",
    "Rourkela",
    "Ratlam",
    "Salem",
    "Sangli",
    "Shimla",
    "Siliguri",
    "Solapur",
    "Srinagar",
    "Surat",
    "Thanjavur",
    "Thiruvananthapuram",
    "Thrissur",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tiruvannamalai",
    "Ujjain",
    "Bijapur",
    "Vadodara",
    "Varanasi",
    "Vasai-Virar City",
    "Vijayawada",
    "Visakhapatnam",
    "Vellore",
    "Warangal"
]
const tierOne = [
    "Hyderabad",
    "Ahmedabad",
    "Bengaluru",
    "Chennai",
    "Delhi",
    "Kolkata",
    "Mumbai",
    "Pune", 
];

module.exports.cities = [
    // ...tierOne,  
    ...tierTwo
];


